const drawer = document.querySelector<HTMLDivElement>("#drawer")
const showprev = document.querySelector<HTMLButtonElement>("#showprev")
const hideprev = document.querySelector<HTMLButtonElement>("#hideprev")
const submitButton = document.querySelector<HTMLButtonElement>("#Submit")
const drawerTable = document.querySelector<HTMLTableElement>("#table")